# Generated by Django 4.2.6 on 2023-12-16 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='category',
            field=models.CharField(choices=[('A', 'ACTION'), ('AD', 'ADVENTURE'), ('D', 'DRAMA'), ('R', 'ROMANCE'), ('C', 'COMEDY')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='status',
            field=models.CharField(choices=[('TR', 'TOP RATED'), ('MW', 'MOST WATCHED'), ('RA', 'RECENTLY ADDED')], max_length=5, null=True),
        ),
    ]
