# Generated by Django 4.2.6 on 2023-12-16 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_movie_category_movie_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='status',
        ),
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.CharField(choices=[('D', 'DRAMA'), ('A', 'ACTION'), ('R', 'ROMANCE'), ('AD', 'ADVENTURE'), ('C', 'COMEDY')], max_length=5, null=True),
        ),
    ]
