# Generated by Django 4.2.6 on 2023-12-19 13:03

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('main', '0006_remove_movie_status_alter_movie_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.CharField(choices=[('A', 'ACTION'), ('R', 'ROMANCE'), ('D', 'DRAMA'), ('AD', 'ADVENTURE'), ('C', 'COMEDY')], max_length=5, null=True),
        ),
    ]
